### ISSUE TITLE
Artist Bio

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#11]
Last one!  Is it possible to grab an artist's bio, ie, this info:

Artist information
Type: Group
Founded: 1985 (39 years ago)
Founded in: Richmond, Virginia, United States

Unless you see an easier way, you can get most of the data here (type isn't included, not sure how to find this):
https://musicbrainz.org/ws/2/artist/f7ccd53a-234c-4800-8d1b-21b201bad1de

That includes a begin-area id, which you can follow:
https://musicbrainz.org/ws/2/area/afaa40c1-2e11-4a9b-9a33-ff0603e3e312?inc=area-rels

**Comment by duck7000** [comment]
In which method do you want this to be included?

The api call in fetchData can be included with area-rels so it might be possible to add it to fetchData

**Comment by GeorgeFive** [comment]
That could work, or maybe make a simple artist method to return data like this in case someone else doesn't care about this info?

**Comment by duck7000** [comment]
In this case it doesn't really matter as all release data is in one method already.
If i can make it work i'll add it to fetchData

**Comment by duck7000** [comment]
Mm i have to rephrase that.
I have not clue how or where you want this info as it is not in the data from fetchData()

Is this something you would want in TittleSearchAdvanced?

**Comment by GeorgeFive** [comment]
That could indeed work.  I'm not terribly picky, as long as I can grab it somehow, I'm happy!

**Comment by duck7000** [comment]
Okay i made something working in a new method that fetches artist bio info.

Just a update, that is all for now but no rush indeed

**Comment by GeorgeFive** [comment]
Sounds good, I'll check it out when you commit it!

**Comment by GeorgeFive** [comment]
I think it works pretty nicely as you have it now.  I'm grabbing the artist bios for artists on a given album.  Most cases it's one band so I have to make one call (if I don't already have the band id in my db), sometimes, it's a v/a, so I have to do multiple calls.  I personally think it's fine as is.

One request though.  For beginArea and endArea, could we get the full area along with musicbrainz's place id's?  For the above example, I'm getting Richmond... I would like to get "Richmond, Virginia, United States".

I ask for their id's for quality.... I mean, there's 41 cities named Springfield in the US alone, so without the id, how will we know the right one?  Just to make it easy, haha.

**Comment by duck7000** [comment]
Mm if i use your example artist id this is all data that is available:

```
stdClass Object
(
    [life-span] => stdClass Object
        (
            [end] => 
            [begin] => 1985
            [ended] => 
        )

    [sort-name] => GWAR
    [disambiguation] => 
    [end-area] => 
    [area] => stdClass Object
        (
            [id] => 489ce91b-6658-3307-9877-795b68554c98
            [type-id] => 
            [iso-3166-1-codes] => Array
                (
                    [0] => US
                )

            [type] => 
            [name] => United States
            [sort-name] => United States
            [disambiguation] => 
        )

    [name] => GWAR
    [type-id] => e431f5f6-b5d2-343d-8b36-72607fffb74b
    [country] => US
    [gender-id] => 
    [begin-area] => stdClass Object
        (
            [type-id] => 
            [sort-name] => Richmond
            [disambiguation] => 
            [name] => Richmond
            [type] => 
            [id] => afaa40c1-2e11-4a9b-9a33-ff0603e3e312
        )

    [ipis] => Array
        (
        )

    [type] => Group
    [gender] => 
    [id] => f7ccd53a-234c-4800-8d1b-21b201bad1de
    [isnis] => Array
        (
            [0] => 0000000110892186
        )

)
```
I don't know where musicbrainz get the detailed info like Virginia?
Place id can be added though.
Maybe they get it through place id?

**Comment by duck7000** [comment]
After some experimenting there is no more data to be fetched so i don't know where they get "Virginia" from.

I will add the id's for beginArea and endArea, that is all i can do

**Comment by GeorgeFive** [comment]
I'm pretty sure they're following the place id... with your results above, I can take that place id and do....

https://musicbrainz.org/ws/2/area/afaa40c1-2e11-4a9b-9a33-ff0603e3e312?inc=area-rels

**Comment by duck7000** [comment]
I've added place id in latest git commit

**Comment by duck7000** [comment]
Maybe i can include that in the results of the first query but it would need another query inside the existing one

**Comment by duck7000** [comment]
I'm working on a separate method (in API.php) for area and area-rels.
It will be include in fetchArtistBio()

It is working but still puzzling how to arrange the data in the results

**Comment by duck7000** [comment]
@GeorgeFive 

I uploaded a few changes to this new method

The output array is re-arranged and contains new data from area relations.
I added all info that i would think it is useful but if you miss something let me know

Info is in the wiki

So check it out if you have the time

To be honest this is a nice distraction from reallity

**Comment by GeorgeFive** [comment]
You know, I went through a whole lot of real world shit last year, and I also found that this stuff really helped my mental state.  So it's not just you!

Ok, so I just checked this out, and got....

    [areaBegin] => Array
        (
            [id] => afaa40c1-2e11-4a9b-9a33-ff0603e3e312
            [city] => Richmond
            [type] => 
        )

    [areaEnd] => Array
        (
        )

    [areaRelation] => Array
        (
            [0] => Array
                (
                    [id] => 02e01cf9-b0ed-4286-ac6d-16989f92ced6
                    [name] => Virginia
                    [type] => Subdivision
                )

        )

Is there a possibility of having multiple items in areaRelation?  I see it's setup as an array... I don't think there would be more than one, but did you see something I didn't?

Also, for type in areaBegin and areaRelation... do you have a list of possible values for this?  Just out of curiosity, I didn't even know about that.

**Comment by GeorgeFive** [comment]
Also, I noticed something.... it seems like some places have an undisplayed county....

80cadd99-f560-41e3-babd-16292bbd248a

returns

    [areaBegin] => Array
        (
            [id] => e794c48d-2e18-4e1a-830c-cdf24a4ba07c
            [city] => Canton
            [type] => 
        )

    [areaEnd] => Array
        (
        )

    [areaRelation] => Array
        (
            [0] => Array
                (
                    [id] => b158fe6f-66af-48f1-90d3-c616db726bd2
                    [name] => Stark County
                    [type] => County
                )

        )

Stark County is a county, not the expected state.  Stark County is in Ohio, so that should be changed.

Born in: Canton, Ohio, United States

I didn't know they had counties, that's cool to have!

**Comment by duck7000** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> Is there a possibility of having multiple items in areaRelation?  I see it's setup as an array... I don't think there would be more than one, but did you see something I didn't?

yes i have seen one with more then one element in releations (joy divison for example)

**Comment by duck7000** [comment]
> Also, for type in areaBegin and areaRelation... do you have a list of possible values for this? Just out of curiosity, I didn't even know about that.

Honestly i haven't seen that type actually contains anything so i don't know what it could be but included it anyway

**Comment by duck7000** [comment]
> Also, I noticed something.... it seems like some places have an undisplayed county....
> 
> 80cadd99-f560-41e3-babd-16292bbd248a Born in: Canton, Ohio, United States
> 
> but it returns
> 
> ```
> [areaBegin] => Array
>     (
>         [id] => e794c48d-2e18-4e1a-830c-cdf24a4ba07c
>         [city] => Canton
>         [type] => 
>     )
> 
> [areaEnd] => Array
>     (
>     )
> 
> [areaRelation] => Array
>     (
>         [0] => Array
>             (
>                 [id] => b158fe6f-66af-48f1-90d3-c616db726bd2
>                 [name] => Stark County
>                 [type] => County
>             )
> 
>     )
> ```
> 
> Stark County is a county, not the expected state. Stark County is in Ohio, so that should be updated.
> 
> They're technically saying: Stark County, Canton, Ohio, United States, but not displaying that first part.
> 
> I didn't know they had counties, that's cool to have! Definitely keep that in, hah.

Mm i have to check what exactly is returned if i use this id, maybe i can find something like state:Ohio

**Comment by duck7000** [comment]
I added state info through a third api call and included sleep(1) to avoid issues
It works with your example.. i hope it always works

**Comment by GeorgeFive** [comment]
I know you're getting sick of this, haha.  But, now it almost seems to return too much for some artists?

Check out Sex Pistols.... e5db18cb-4b1f-496d-a308-548b611090d3.... there's 33 arearelations.  The first one is right (England), but the other 32 are irrelevant... they seem to be getting every part of London from this page:

https://musicbrainz.org/area/f03d09b3-39dc-4083-afd6-159e3f0d462f

Also, could we get state place ids?

This is getting confusing, hah.  If counties makes it too difficult, I don't terribly need that.  It's interesting, but it seems to make things more complicated.

**Comment by GeorgeFive** [comment]
Also, it may be wise to move country into the area array.

I thought the main country would suffice, but that doesn't always line up...

https://musicbrainz.org/artist/090e9c0a-6767-49e0-8f51-84a43226a174

Born in: Harrow, London (Greater London), England, United Kingdom
Area: Australia

**Comment by GeorgeFive** [comment]
Ok, so this isn't easy, but I did find an old thread that makes things make a little more sense.

https://community.metabrainz.org/t/retrieving-country-name-from-city-areas-using-api/145697

Start with the begin area returned in a normal artist search, follow that area ID, pick the one that says "backward", follow that, etc etc until you hit country.  There's your complete string.  Throw in some id's, and... profit?!

**Comment by duck7000** [comment]
Well to be honest this is going the wrong way as we are drifting away too far.

I think we should settle for only country and city (maybe include state like my latest commit) but stop there.

Your last comment makes it even more complicated, so complicated, that this would need a total new method just to get all country, state, Provence,county etc.

So if you still want all area info we have to design a new method just for area info alone, it is too complicated to include it in fetchArtistBio directly. If so i will remove everything area related and will be moving this to the new method. But yes this is no easy task, but it will keep my mind occupied

**Comment by duck7000** [comment]
country is separate because this is not related to begin or end area, it is common i guess

**Comment by duck7000** [comment]
mm i tested your last link and it works.. but only for specific country, nothing else is returned.
So it does not include state or city or county info.
I tried with GWAR and the output is the same what country already had, but this is indeed specific begin area country not common country.

It is very, very complicated!
It would be much easier if musicbrainz combined area information! Now it is spreaded through out all different api parts

**Comment by GeorgeFive** [comment]
Yeah, I had noticed that we get country up alongside name and all, and then area down below.  I figured I could just combine the two, but then I found that they don't always match.  So in that case, combining would give something dumb like:

Born in: Harrow, London, England, Australia

I'm currently downloading a copy of their database to see if they have the areas database in there.  If they do, I could make this really easy and just cache a copy of that and do my own lookups.

That's about where I'm at on ideas right now, this did indeed get complicated, haha.

**Comment by duck7000** [comment]
At least it works for begin area country, i'll assume it also will for end area country.
So i can do that instead of common country?

We can keep the city or state info but i agree that it sometimes not accurate

That is all i can think of

**Comment by GeorgeFive** [comment]
I think that would work for now.... from what I'm reading, they know about this issue and plan to update the API.  So when they really do fix it, maybe this will be easier?

Funny, I looked into their db... even that idea won't work, they didn't release the connections in any of the dbs I looked at.

**Comment by duck7000** [comment]
Mm spoke too soon, for joy division country doesn't work.. It doesn't have a type country

So 2 options left, as this leads to nowhere i'm afraid

Keep it like it is now
(but do note that the area info is based on begin area, so there is no end area info) and even that info isn't always accurate.
And the "subdivision" part doesn't work with the sex pistols as you showed above.
So this isn't even half working and it might or might not be accurate at all

Or i remove the whole area part and only use the common country (this would be the best option as it is accurate)
It may contain a city name or something, i can include that too.

**Comment by GeorgeFive** [comment]
Yeah, I'd say just keep it simple for now, this got a little more complicated than I thought it would.  I'm thinking I might be able to do some magic on my end to trail it down and get the info from their area results, and in theory, I'd only have to do it once per location (Salford's relations will never change).  It may be some work, and I might give up halfway through if it's too much, but the idea is there, haha.

**Comment by duck7000** [comment]
I removed the area part in latest commit, so this can be closed, at least for now.

**Comment by duck7000** [comment]
I'm glad you worked it out!

But this is not something i would include in the musicBrainzPHP library.
For that we have to wait until musicbrainz fix things the right way haha

would you like to keep this issue open? Otherwise it will slip our minds

**Comment by GeorgeFive** [comment]
Yeah, I think keeping it open is a good idea.

One thing I just noticed, that I think I overlooked due to all of the above, is that type is not being returned in begin/end area.

    [areaBegin] => Array
        (
            [id] => a2993fdb-6cc6-49da-abe6-831142053fd1
            [city] => Fort Lauderdale
            [type] => 
        )

**Comment by duck7000** [comment]
well that might be because there is not data for type, and i don't have seen it ever does either.

so it may be better to remove it i guess?

**Comment by GeorgeFive** [comment]
Hmm.... ok, I didn't even know this was unavailable outside of area lookup.  Type is available there, but not in this lookup.  Weird how certain parts are available in one lookup, but not the other.

And changing to name shouldn't be a huge issue, it does make more sense.  I just call it "area" in my database, hah.

**Comment by duck7000** [comment]
what i meant is that type is available in begin-area but it doesn't contain any data, ever so removing is probably the best.

I will change city to name

**Comment by duck7000** [comment]
done in latest commit

**Comment by GeorgeFive** [comment]
The never-ending thread continues, hah.  I noticed that $bio['areaBegin']['id'] is not getting reset between calls when adding a v/a album if an artist does not have an areabegin set.  I assume areaend may do the same, but I have not tested.

In this example, everything for Steps is correct.  The next two bands do not have areabegin set on musicbrainz, so the previous data from Steps carries over.

Array
(
    [name] => Steps
    [id] => 19659aa7-cd3a-4bfe-bca0-6943e9e5c6e0
    [type] => Group
    [gender] => 
    [country] => United Kingdom
    [disambiguation] => British Euro-Pop group
    [lifeSpan] => Array
        (
            [begin] => 1997-05-07
            [end] => 
            [ended] => 
        )

    [areaBegin] => Array
        (
            [id] => f03d09b3-39dc-4083-afd6-159e3f0d462f
            [name] => London
        )

    [areaEnd] => Array
        (
        )

)
Array
(
    [name] => Jonas
    [id] => 7c68d22f-8594-4aab-aadd-19e76373f8a3
    [type] => 
    [gender] => 
    [country] => Sweden
    [disambiguation] => Swedish house, track "Parta lite granna"
    [lifeSpan] => Array
        (
            [begin] => 
            [end] => 
            [ended] => 
        )

    [areaBegin] => Array
        (
            [id] => f03d09b3-39dc-4083-afd6-159e3f0d462f
            [name] => London
        )

    [areaEnd] => Array
        (
        )

)
Array
(
    [name] => Booster
    [id] => df7731bb-9e8e-40ed-af4e-6e785b60adf6
    [type] => Group
    [gender] => 
    [country] => 
    [disambiguation] => 1998 euro house act, track: 'Your Lovin''
    [lifeSpan] => Array
        (
            [begin] => 
            [end] => 
            [ended] => 1
        )

    [areaBegin] => Array
        (
            [id] => f03d09b3-39dc-4083-afd6-159e3f0d462f
            [name] => London
        )

    [areaEnd] => Array
        (
        )

)

**Comment by duck7000** [comment]
Mm you are right of course but this is happening if the user re use the class instance. For this method you call the class without a parameter and call the method with an id. If you call the same method again without doing a new class instance this will happen.

There are 3 ways to solve this:

Set up front inside the method those vars again to empty array
Remove the if statements from beginArea, endArea and lifeSpan (this will cause an array with id, name with no values)
Set at the end of this method those vars back to empty array

Not sure what is the best approach?

**Comment by duck7000** [comment]
I choose for option 1, fixed in latest commit (i hope)

**Comment by GeorgeFive** [comment]
Ok, this is working now, but now I get another issue when adding a v/a album (normal one-artist albums work ok):

album id - 852f2c41-bb63-49cb-963c-f20b0fcc6bf2

[25-Jul-2024 11:30:29 EST] PHP Fatal error:  Uncaught Exception: Failed to retrieve query in classes/MusicBrainzPHP/src/Music/API.php:249
Stack trace:
#0 classes/MusicBrainzPHP/src/Music/API.php(296): Music\Api->execRequest('https://musicbr...')
#1 classes/MusicBrainzPHP/src/Music/API.php(95): Music\Api->checkCache('3037bd18-0079-4...', 'https://musicbr...', 'title', '_bio')
#2 classes/MusicBrainzPHP/src/Music/Title.php(536): Music\Api->doArtistBioLookup('3037bd18-0079-4...')
#3 admin/get_musicbrainz_info.php(779): Music\Title->fetchArtistBio('3037bd18-0079-4...')
#4 admin/get_musicbrainz_info.php(63): doAddAlbum('1bbbe5a8-fe9f-4...')
#5 admin/get_musicbrainz_info.php(15): main('1bbbe5a8-fe9f-4...', 'addalbum')
#6 {main}
  thrown in classes/MusicBrainzPHP/src/Music/API.php on line 249

**Comment by duck7000** [comment]
They do not like more request than one per second so keep that in mind, they will sooner or later block you

**Comment by GeorgeFive** [comment]
Yeah, I took all the sleep calls out while testing various things, I'm impatient, haha.

**Comment by duck7000** [comment]
@GeorgeFive 
Do you want/have any new info concerning the original question of this thread?
I think we should close this as we both can't work it out if musicBrainz does not fix this, agree?

**Comment by GeorgeFive** [comment]
Agreed. I currently grab the area ID from artist and then store it in an areas table, and then lookup that area for parents, and and and... it works, but it's a bit clunky.  Would be nice if they sorted this out, but my way works.
