### ISSUE TITLE
titleSearchFormat

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#12]
I know you're busy with real world stuff, but I just wanted to put this here for whenever you get time.  No rush!

In the config file, could we have a new option for titleSearchFormat for "all" to get all formats?

Also, 12" Vinyl is a bad option, as the quote interferes with the opening and closing quotes.  Even escaped, it doesn't work properly.

**Comment by duck7000** [comment]
I'll remove all vinyl options accept vinyl itself, i wasn't even sure 12" Vinyl would work but left it in anyway

Maybe you can use single quotes like this '12" vinyl'? Honestly i haven't tested that either, vinyl would definitely work

All formats.. maybe, i have to think about that.

Even if i have little time you can indeed still open new issues but i might response to it or not

**Comment by duck7000** [comment]
Vinyl options are removed in latest git.

Thinking about the issues here might keep my mind of for a little while from real world issues

**Comment by GeorgeFive** [comment]
I did try single quotes, got no results back with it.  Vinyl does work, but it won't return 12" Vinyl as a type.

Example - https://musicbrainz.org/release-group/fc926256-51fe-3f21-aa74-6ece8865f491

The two releases there that are CD work when config is set to CD, no issues there.  However, when config is set to vinyl, the four 12" Vinyl releases are not returned.

**Comment by duck7000** [comment]
Mm i have to find out how to use 12" vinyl as a format option in the query string, it is a valid type but we must be something wrong or missing something

**Comment by GeorgeFive** [comment]
My main reason for wanting an "all" option is to just return everything, even if I don't know the format (and it's annoying to change the config file even if I do know it).

Example here, my config was set to cd... I wanted to find this - https://musicbrainz.org/release/a5943db6-6116-4d81-bfb5-e88a4c8b021d

Even in a best case scenario, I'd still have to edit the config file and change it to vinyl to get that to return.  If someone doesn't care about all formats, they can leave config set to cd or whatever... but if they want everything, there's an option.

**Comment by duck7000** [comment]
I found this online

`[https://musicbrainz.org/search?query=artist%3A"Don+Rendell"+AND+format%3A"12\"+Vinyl"+AND+primarytype%3AAlbum+AND+-secondarytype%3Acompilation&type=release&limit=25&method=advanced](https://musicbrainz.org/search?query=artist%3A%22Don+Rendell%22+AND+format%3A%2212%5C%22+Vinyl%22+AND+primarytype%3AAlbum+AND+-secondarytype%3Acompilation&type=release&limit=25&method=advanced)`

"12\"+Vinyl" should apparently work

And it might be better to use format id (didn't occur to me that i can use this)? I don't have a clue if such a array or list exists

**Comment by duck7000** [comment]
All option is not difficult, just leave out the format part in doSearch()
I'll try to fix that

**Comment by GeorgeFive** [comment]
Ok, the + did make it work, so there's that accomplished, haha.  I'm not too concerned with the limit, as what I want is usually towards the top anyway.

There is a list of formats, but they don't include the IDs with them.  It's a huge list....

https://wiki.musicbrainz.org/Release/Format

**Comment by duck7000** [comment]
Yes i'm aware of this huge list.. and indeed no id's so for now i'll leave it like it is
I picked the most used ones for the config list.

I'll try that later on

**Comment by duck7000** [comment]
I added option All in config (All is case sensitive!) in latest git commit

Or might it be better to choose something else for option All?
-1
null
empty string

**Comment by duck7000** [comment]
I can, if i figured out the vinyl stuff, make the format a search parameter?
Would that help in the sense that you don't have to change the config anymore.
the default will remain cd

**Comment by GeorgeFive** [comment]
All works fine, thanks!  A search parameter may help others, but honestly, I'm going to leave mine set to All and that works exactly how I want it.  I'll mostly be doing artist searches with this and doing things that way, but I do the occasional album search for soundtracks and v/a compilations and such.

**Comment by duck7000** [comment]
Okay I'll leave it like it is.

I'll improve the all parameter to be case insensitive as the other options are case insensitive

**Comment by duck7000** [comment]
I made the all format setting in config case insensitive, so it matches other options.

And i added back the vinyl options with the proper encoding and escape in place so it is usable

Latest git commit contains the changes
