### ISSUE TITLE
releasegroup date

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#13]
Hopefully a quick and easy one!

In titlesearchadvanced, we have:

[date]                (string) release date of this release group

Could we also get that in title?  It doesn't have to replace the date that is already there, just as an added option.

This way, I could add the version of an album with the most details (a reissue or something), but also have the original date.  For example, if I added this version:

https://musicbrainz.org/release/56ecbd32-fc30-4843-9274-54fcd0750dd3

...I would get that particular version's release date of 2014.  Some may want that (so keep the original date option), but some may want the original date tied to this album.

**Comment by duck7000** [comment]
Mm quick and easy.. where did i hear this before haha

So you want the release date of the common album and the specific release date of a specific version.. right i'll see if i can come up with something

**Comment by GeorgeFive** [comment]
Yep!  It currently shows the specific date of that specific version, and I say leave that, but add in the common version (which is already available in advanced).  Hopefully quick, haha.

**Comment by GeorgeFive** [comment]
Another hopefully easy!

Can I get disambiguation from title, copied over to TitleSearchAdvanced->releaseGroupReleases?  Same functionality, just need it over there as well.

My frontend is almost done, can you tell!?  hah

**Comment by duck7000** [comment]
> Another hopefully easy!
> 
> Can I get disambiguation from title, copied over to TitleSearchAdvanced->releaseGroupReleases? Same functionality, just need it over there as well.
> 
> My frontend is almost done, can you tell!? hah

It may be better to make separate issues, it is much easier to keep the oversight, so would you please make a separate one for this?

**Comment by duck7000** [comment]
First release date is added in latest commit

**Comment by duck7000** [comment]
> > Another hopefully easy!
> > Can I get disambiguation from title, copied over to TitleSearchAdvanced->releaseGroupReleases? Same functionality, just need it over there as well.
> > My frontend is almost done, can you tell!? hah
> 
> @GeorgeFive It may be better to make separate issues, it is much easier to keep the oversight, so would you please make a separate one for this?

This info is not available in the results of releaseGroupReleases, sorry

**Comment by GeorgeFive** [comment]
Thanks!
