### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#14]
I'm slowing down on stuff to bring over, nice!  hah.

Could we add aliases to bio, keeping "type", "locale", "begin" "end date"?
https://musicbrainz.org/ws/2/artist/5dfdca28-9ddc-4853-933c-8bc97d87beec?inc=aliases

**Comment by duck7000** [comment]
I'll try to find/add it..

**Comment by duck7000** [comment]
It is available and working so i can add it to bio

type-id, ended and sort-name is not of interest i suppose? 

[type] => Search hint
[primary] => 
[ended] => 
[locale] => 
[begin] => 
[type-id] => 1937e404-b981-3cb7-8151-4c86ebfc8d8e
[name] => Manson Marilyn
[end] => 
[sort-name] => Manson Marilyn

**Comment by duck7000** [comment]
This is added in latest git commit

**Comment by GeorgeFive** [comment]
Perfect, thanks!
