### ISSUE TITLE
fetchArtistBio - Area

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#15]
Not really related to the other issue, but kinda close.

Most artists have a begin area, and we get that fine.  However, some artists do not have that, but they do have an area.  Just to make it more fun, some of the areas are more generic in this case.

Perfectly fine example: https://musicbrainz.org/ws/2/artist/a8806b5c-3ee0-4277-94d3-1a5427a7707c

```
<area id="8a754a16-0027-3a29-b6d7-2b40ea0481ed">
<name>United Kingdom</name>
<sort-name>United Kingdom</sort-name>
<iso-3166-1-code-list>
<iso-3166-1-code>GB</iso-3166-1-code>
</iso-3166-1-code-list>
</area>
<begin-area id="057ce294-2684-46fd-aee1-4d8c6b4bf4ef">
<name>Belfast</name>
<sort-name>Belfast</sort-name>
<iso-3166-2-code-list>
<iso-3166-2-code>GB-BFS</iso-3166-2-code>
</iso-3166-2-code-list>
</begin-area>
```

Other bands do not have begin-area, but do have area: https://musicbrainz.org/ws/2/artist/2a411a5f-6d0f-405d-830c-a1a0595c9944

```
<area id="a326cade-eef7-4a85-b683-1f7e06330e0e">
<name>Millsboro</name>
<sort-name>Millsboro</sort-name>
</area>
```

Could we get area as a separate string?  Or, maybe we could be easier with it, and if begin-area isn't set, but area is, return that instead?

**Comment by duck7000** [comment]
Mm area is already there, but i named it country?

`$this->bioCountry = isset($data->area->name) ? $data->area->name : null;`

area-name is already been used so both area and begin-area are there.
So you can choose what you want to use.

And area is not the same as begin-area, area is the overall area (like a country, state or part of the world) where begin-area is more specific (a city, county) So returning area info instead of begin-area is not wise i suppose

I can include area-id (this is not added) if you want?

**Comment by GeorgeFive** [comment]
Ok, I thought country would have been the actual country (ie, United States) which comes from search results.  This explains some things I noticed in my db, haha.

I did notice some bands have more specific area info in the area field as opposed to the begin area, which is weird...

https://musicbrainz.org/artist/5db9f569-cadd-4f8b-b460-d4031b0b3716

Founded in: New York, United States
Area: Long Island City, New York, New York, United States

Ok, so I think bringing over the ID will help with one issue there.  I've sort of went live with this on my site now, and of course, this is when I start noticing little things like this, haha.

**Comment by duck7000** [comment]
This kind of issues always only surface when you think that everything is ready hah

I'll add area-id, possibly with its own array just like begin-area with name and id

**Comment by duck7000** [comment]
Changes are uploaded in latest git

I added an array just like begin area with name and id.
I removed country.
The output array order is changed and added area

**Comment by GeorgeFive** [comment]
Looks good, but I noticed the old bug of area / begin-area ids not being reset if the next band in the array does not have an area set.

Adding V/A album - artist 1 has area set - gets it properly - artist 2 has nothing set - we get the info from artist 1.

**Comment by duck7000** [comment]
Mmm i think you made a "thinking" error hah
If you use 2 artists from the **same** country then yes this appears to be that the data is not refreshed. However in that case it IS refreshed but with the same data as the country and id is the same.

In this example i used 2 artists from different country's (first is marilyn manson, second is AC/DC):

```
$music = new \Music\Title("");
$data = array('5dfdca28-9ddc-4853-933c-8bc97d87beec', '66c662b6-6e2f-4930-8610-912e24c63ed1');
foreach($data as $value) {
    echo '<pre>';
        print_r($music->fetchArtistBio($value));
    echo '/<pre>';
}
```

This will get this output:

```
/

Array
(
    [name] => Marilyn Manson
    [id] => 5dfdca28-9ddc-4853-933c-8bc97d87beec
    [type] => Group
    [gender] => 
    [disambiguation] => the band
    [lifeSpan] => Array
        (
            [begin] => 1989
            [end] => 
            [ended] => 
        )

    [area] => Array
        (
            [id] => 489ce91b-6658-3307-9877-795b68554c98
            [name] => United States
        )

    [areaBegin] => Array
        (
            [id] => a2993fdb-6cc6-49da-abe6-831142053fd1
            [city] => Fort Lauderdale
            [country] => 
            [type] => 
        )

    [areaEnd] => Array
        (
        )

    [areaRelation] => Array
        (
        )

    [aliases] => Array
        (
            [0] => Array
                (
                    [name] => Manson Marilyn
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [1] => Array
                (
                    [name] => Mar1lyn Man5on
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [2] => Array
                (
                    [name] => Marilin Manson
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [3] => Array
                (
                    [name] => Marilyn Manson
                    [type] => Artist name
                    [begin] => 1992
                    [end] => 
                    [locale] => 
                )

            [4] => Array
                (
                    [name] => Marilyn Manson & the Spooky Kids
                    [type] => Artist name
                    [begin] => 1989
                    [end] => 1992
                    [locale] => 
                )

            [5] => Array
                (
                    [name] => Marilyn Manson and the Spooky Kids
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [6] => Array
                (
                    [name] => Mariyln Manson
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [7] => Array
                (
                    [name] => Marylin Manson
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [8] => Array
                (
                    [name] => The Spooky Kids
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [9] => Array
                (
                    [name] => marily manson
                    [type] => 
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [10] => Array
                (
                    [name] => マリリン・マンソン
                    [type] => Artist name
                    [begin] => 
                    [end] => 
                    [locale] => ja
                )

        )

)
/

/

Array
(
    [name] => AC/DC
    [id] => 66c662b6-6e2f-4930-8610-912e24c63ed1
    [type] => Group
    [gender] => 
    [disambiguation] => Australian hard rock band
    [lifeSpan] => Array
        (
            [begin] => 1973-11
            [end] => 
            [ended] => 
        )

    [area] => Array
        (
            [id] => 106e0bec-b638-3b37-b731-f53d507dc00e
            [name] => Australia
        )

    [areaBegin] => Array
        (
            [id] => 3f179da4-83c6-4a28-a627-e46b4a8ff1ed
            [city] => Sydney
            [country] => 
            [type] => 
        )

    [areaEnd] => Array
        (
        )

    [areaRelation] => Array
        (
        )

    [aliases] => Array
        (
            [0] => Array
                (
                    [name] => AC DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [1] => Array
                (
                    [name] => AC-DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [2] => Array
                (
                    [name] => AC.DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [3] => Array
                (
                    [name] => AC/DC
                    [type] => Artist name
                    [begin] => 1973-11
                    [end] => 
                    [locale] => 
                )

            [4] => Array
                (
                    [name] => AC?DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [5] => Array
                (
                    [name] => ACDC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [6] => Array
                (
                    [name] => AC\DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [7] => Array
                (
                    [name] => AC|DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [8] => Array
                (
                    [name] => AC⚡DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [9] => Array
                (
                    [name] => AC⚡︎DC
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [10] => Array
                (
                    [name] => Acca Dacca
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

            [11] => Array
                (
                    [name] => Akka Dakka
                    [type] => Search hint
                    [begin] => 
                    [end] => 
                    [locale] => 
                )

        )

)
/


```
So my conclusion is that it is working, unless you can convince me otherwise?

**Comment by GeorgeFive** [comment]
I'm not at home right now to show code, but what I did was add a v/a album and then run foreach on track artists to get their info. Band 1 had info set, everything was good,  bands 2 and 3 had absolutely no info on mb, so we get the same info from band 1 for them. Then band 4 has info, so we get the proper results for them... 5 has nothing, so we get band 4's info.

$music did use an id though, as I was adding an album and getting info for that albums artists.

**Comment by duck7000** [comment]
Mmm it might be because i use $data in multiple methods?
At first i didn't think of using multiple functions in this class so it doesn't  matter

I can change those $data to different names, see if that fixes the problem

**Comment by duck7000** [comment]
names are changed in latest commit

**Comment by duck7000** [comment]
The Artist class is working here but i'll wait for your response

**Comment by GeorgeFive** [comment]
I'll be home in about six hours, but until then, I'm kinda stuck, haha.

**Comment by duck7000** [comment]
I did upload the new Artist class.
You can call the class with an artistId just like Title class

```
$music = new \Music\Artist("5dfdca28-9ddc-4853-933c-8bc97d87beec");
$music->fetchArtistBio();
```

fetchArtistBio is still available in Title class but if this is working for you (it did in my tests) i will remove it from Title class.

A separate class is much better (i should have done this sooner!) But alright i'm an amateur haha 

I'm thinking to do the same for the cover images, cleaner in its own class file

**Comment by GeorgeFive** [comment]
I'm still getting the same issue.... I'm even calling it over again from scratch.

I tried to chop a huge function down to bite-sized skimming, but you get the idea:

```
        $music = new \Music\Title($searchterm);
        $results = $music->fetchData();
        $tracks = $results['media'];

         foreach ($tracks[$i]['tracks'] as $track) {
            foreach ($track['artist'] as $trackart) {
                $bio = new \Music\Artist($trackart['id']);
                $bio->fetchArtistBio();

```

I pulled in this band first: https://musicbrainz.org/artist/51c0df90-bf41-4058-a673-91fffc35ff70

Correctly fetched
Area: Ontario, Canada

Next band was: https://musicbrainz.org/artist/838787b5-3d91-485f-83cd-a01c3f66e8d2

Pulled in data from previous band because they have nothing set on mb - Area: Ontario, Canada

**Comment by duck7000** [comment]
Mm yes what you wrote in the email doesn't seem right indeed.

yes call it like that, the only difference is that you now have to initiate the class every time, just like the title class.
This way it is much more easier and it is separated in classes and the data is always refreshed so data remaining from a previous call is not possible anymore.

please test some more, if it is working i will remove artist bio part from Title class.

I will do the same for coverArt, this belongs to its own class rather than inside Title class as well

**Comment by GeorgeFive** [comment]
I haven't ran into any problems with this, so yeah, I think it's safe for you to remove it!

**Comment by duck7000** [comment]
okay will do
