### ISSUE TITLE
Cover art is now a separate class

### ISSUE THREAD

**Issue by duck7000** [duck7000/MusicBrainzPHP#16]
@GeorgeFive
I made the cover art fetching in a new separate class.
From now on fetchData will use this new class so check it out if you have the time.
The working should be the same so if you don't notice anything different it is fine.

For now the existing method in Title class is still there in case you need it but i'll remove it when it is proven to be working.

**Comment by GeorgeFive** [comment]
Looks good to me... as mentioned, I don't see a difference at all, hah.

**Comment by duck7000** [comment]
Nice, i'll remove it from Title class.

I never understood why most programmers use a lot of different files and classes but now i do. Much easier to work with.

**Comment by duck7000** [comment]
i removed cover art methods from title class in latest commit

**Comment by GeorgeFive** [comment]
Looks good to me!

**Comment by duck7000** [comment]
Thanks for testing

One question remains:
Now we have a separate class for the cover art should we remove that call from fetchData() and instead call Cover class in our own code?
Or leave it like it is?

**Comment by GeorgeFive** [comment]
I would probably say leave it as is, it's nice and easy as is and would have less confusion, I think.

**Comment by GeorgeFive** [comment]
One thing I've been thinking about changing in my own code: this always returns http:// links, but I'd like to use https.  I understand that's on their end and that's how they return it, so I was thinking of doing a quick rewrite in my own code to force https, unless you'd like to put that in the class?

**Comment by duck7000** [comment]
Okay i'll leave it like it is.

I checked the link, sure it is http but after redirect it is returned as https so really it doesn't matter as the re direct link is the one we actually want?
The archive.org link from re direct is https, that is the link to the actual image.

**Comment by GeorgeFive** [comment]
This is true, but I do a hotlink on the returned image url when I want to compare my db data vs their live data, and http makes this hotlink screw up and give browser warnings from time to time ("not secure").  I do end up storing the image on my own server, but the one check causes some issues at random intervals.

**Comment by duck7000** [comment]
Ah i see what you mean.

I can change http to https in the output urls (that is not very hard) it won't bother other users as the re direct link is the same anyway

I'll let you know when this is done

**Comment by GeorgeFive** [comment]
Thanks!  Yeah, I know it's a pretty simple change, I was just going to do it on my own code, but then I thought it might help at least one other person, so why not include it, haha.

**Comment by duck7000** [comment]
https is added in latest commit

**Comment by GeorgeFive** [comment]
Thanks!

**Comment by duck7000** [comment]
@GeorgeFive 

So this is working i guess and can be closed?

**Comment by GeorgeFive** [comment]
Yep!

**Comment by duck7000** [comment]
Thanks for testing!
