### ISSUE TITLE
http / https in cover art

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#18]
I think function checkHttp needs to be rewritten a bit... I've noticed some albums are returning cover arts with https, while others still use http.

This returns https - https://musicbrainz.org/release/f2c770bc-8cdc-4612-8d50-97f5f59a71e4
This returns http - https://musicbrainz.org/release/70d3fc8a-8f66-3d9f-90a0-19007f5b081b

The problem is that in the first example, the cover url is returned as:
httpss://coverartarchive.org/release/f2c770bc-8cdc-4612-8d50-97f5f59a71e4/39113742801-500.jpg

Note the httpss

**Comment by duck7000** [comment]
Mmm sharp haha

I assumed that it will always return http and so i add s to it, i guess this is not working in all cases as you prove.

I'll look in to this

**Comment by duck7000** [comment]
@GeorgeFive 
I fixed this in latest commit.
From now on i replace the part before : with https so this issue can no longer occur

Can you check if this works?

**Comment by GeorgeFive** [comment]
Perfect, thanks!
