### ISSUE TITLE
Caching on image urls

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#20]
As you probably know, the internet archive suffered a ddos attack which interfered with our album cover images.  They're still recovering from this, so every now and then, it will return null for images instead of the expected url.  The album does have an image, but we get a server error, which results in us caching null for the url.

I don't want to disable caching entirely, but if an album returns no image urls, could we not cache that and instead try again when / if the page is refreshed?

**Comment by duck7000** [comment]
mmm this is a nasty problem, it was never designed to consider the possibility of a server error i'm afraid.

I'm not sure if or how i can do something about this.

**Comment by GeorgeFive** [comment]
Gotcha... I haven't dug into the code, but was wondering if it would be as simple as...

if (isset($cover)) { docache } else { donotcache }

**Comment by duck7000** [comment]
Perhaps, but that doesn't "solve" the problem, the hope is in that case that the next time you call that method it might work. So not a real solution, it only prevents null saved as cache.

i'll think about it

**Comment by duck7000** [comment]
Is this getting better over time?
I've read that they have almost everything back on track except it is read only

I can make something in Api class checkCache() that checks if $data == false (404 so not exists) and if true not write to cache?

It still feels not a "solution" though

**Comment by GeorgeFive** [comment]
It does seem to be a little smoother now, though I haven't touched it much this weekend.  As of Thursday/Friday, things seemed 90% working.  When I reported this, it was maybe every 10 page loads that it would screw up, so at that point, it was getting annoying, haha.

**Comment by GeorgeFive** [comment]
Going to close this, as it really isn't an issue anymore.
