### ISSUE TITLE
Title and CoverArt class overhaul, there are user aditions, no changes

### ISSUE THREAD

**Issue by duck7000** [duck7000/MusicBrainzPHP#21]
@GeorgeFive

Title class:

1. Fixed bug with annotations not been fetched (due to multiple typos..)
2. Fixed bug rounding errors on total play length, now it properly rounds to the correct value (in seconds)
3. Redesigned and improved code in Title class

CoverArt class

1. Added a lot of missing checks, it is a miracle that there where no errors or warnings hah
2. Added booklets to the output array, those are in a separate array as there are usually more than one
3. Added 1200 pixels thumbnails to the output array

Wiki page is updated as well

If there are any bugs, issues or missing features let me know here

**Comment by GeorgeFive** [comment]
What are the user changes?

This class is actually pretty solid even before this... I occasionally get MB errors, but we can't really help that, haha.

**Comment by duck7000** [comment]
Basically only point 2 and 3
So in theory there shouldn't be other user changes but i changed a lot and added numerous checks that where missing.
CoverArt returns now false if there is no image data but that doesn't change the output from fetchData()

**Comment by GeorgeFive** [comment]
Not seeing any issues, and I actually didn't have to update my code at all.

**Comment by duck7000** [comment]
> and I actually didn't have to update my code at all.

Jep that is correct hah
You only have to update your code if you are planning to use booklets or 1200 pixel thumbnails

Nice that it works like expected

**Comment by GeorgeFive** [comment]
Oh ok, yeah, the title threw me off a bit.  I thought you meant something had changed that required changes on my end, like a class name change or something.  Which is why I was wondering why the hell I couldn't find what I needed to change before uploading the new files, haha.

**Comment by duck7000** [comment]
sorry about that, and i changed the issue title.

This issue can be closed as it is all working, additions are in wiki
