### ISSUE TITLE
titleSearch class overhaul with user changes!

### ISSUE THREAD

**Issue by duck7000** [duck7000/MusicBrainzPHP#22]
@GeorgeFive
User changes:

1. Changed type to primaryType in output array, to distinguish from secondaryType
2. label is now array(id: int, name: string) and contains all labels instead of only the first one

Additions
1. Added secondaryType as indexed array() which includes all secondary types
2. Added trackCount this is the total track count of found item

Further there are a lot of code improvements hopefully without user changes (there shouldn't be)

**Comment by GeorgeFive** [comment]
All good on my end!

**Comment by duck7000** [comment]
Nice, thanks for testing!
