### ISSUE TITLE
Title int and not a string

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#23]
https://github.com/duck7000/MusicBrainzPHP/commit/a99ed0573950a3ed81019727c211c347812c38ae

This messed up some albums without proper tracknumbers, ie: https://musicbrainz.org/release/9233051e-df20-43b2-b743-c862b9510c94

Before this commit, it would properly return A1, A2, etc... now it just returns 0.

**Comment by duck7000** [comment]
Owh i didn't see any harm to convert to int but apparently there is.

I will change that back

**Comment by GeorgeFive** [comment]
Sounds good!  I also noticed at least one album with roman numerals for the tracklist, though I can't remember what it was off the top of my head.  Weird stuff sometimes.

**Comment by duck7000** [comment]
Thanks for testing and reporting this.
The difference between a developer and user is sometimes not the same hah
