### ISSUE TITLE
Cover art not returning all sizes

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#3]
Sometimes it works, sometimes it doesn't.  Here's an example where it doesn't:

album id - 97a6001c-24fb-4f3d-8bec-f4c2c835b53f

            [front] => Array
                (
                    [id] => 10293862115
                    [originalUrl] => http://coverartarchive.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f/10293862115.jpg
                    [thumbUrl] => 
                    [mediumUrl] => 
                )

But the other sizes do exist...
https://musicbrainz.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f/cover-art

But then, another album does return all...

id - 095e2e2e-60c4-4f9f-a14a-2cc1b468bf66

            [front] => Array
                (
                    [id] => 22307139959
                    [originalUrl] => http://coverartarchive.org/release/095e2e2e-60c4-4f9f-a14a-2cc1b468bf66/22307139959.jpg
                    [thumbUrl] => http://coverartarchive.org/release/095e2e2e-60c4-4f9f-a14a-2cc1b468bf66/22307139959-250.jpg
                    [mediumUrl] => http://coverartarchive.org/release/095e2e2e-60c4-4f9f-a14a-2cc1b468bf66/22307139959-500.jpg
                )

**Comment by duck7000** [comment]
Mm this is interesting though

It might be because i search on a specific server, not the main server. The problem with the main server is that the url's multiple times re-directs.
The first redirect is 307, after that there are more redirects with a different return status.

So 2 options
I am going to use the main server and set curl followredirects to enable

Or if the id is always found construct the urls and test them to not 404

The first option is the best but more work, i look in to this.

**Comment by duck7000** [comment]
After changing to default server and added the redirect option to curl it still don't work.

This is interesting statement on musicBrainz api documentation:
object containing the keys "250", "500", and "1200" linking to thumbnails of those sizes (in pixels); "small" and "large" are deprecated keys and are equivalent to "250" and "500", respectively

It clearly state that keys small and large are deprecated so i change my function to use 250 and 500.
However in your example there is no 250 or 500 fieldname.. only the "deprecated" small and large..

`object(stdClass)#470 (2) { ["images"]=> array(1) { [0]=> object(stdClass)#468 (9) { ["types"]=> array(1) { [0]=> string(5) "Front" } ["front"]=> bool(true) ["back"]=> bool(false) ["edit"]=> int(32868688) ["image"]=> string(87) "http://coverartarchive.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f/10293862115.jpg" ["comment"]=> string(0) "" ["approved"]=> bool(true) ["id"]=> string(11) "10293862115" ["thumbnails"]=> object(stdClass)#469 (2) { ["large"]=> string(91) "http://coverartarchive.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f/10293862115-500.jpg" ["small"]=> string(91) "http://coverartarchive.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f/10293862115-250.jpg" } } } ["release"]=> string(67) "http://musicbrainz.org/release/97a6001c-24fb-4f3d-8bec-f4c2c835b53f" } `

So what is wise to do, still rely on a deprecated fieldname or make my function deal with both?
I tent to the last option all though this is more work

**Comment by duck7000** [comment]
I made extra method to check the field names so both text and number versions are supported with default for numbers and text as second option.

I will upload it soon

**Comment by duck7000** [comment]
coverArt is fixed in latest git
