### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by duck7000** [duck7000/MusicBrainzPHP#4]
Caching is re implanted and i'm currently working on how to use it in the different methods.

**Comment by duck7000** [comment]
I've got caching working on doReleaseGroupSearch()
It needs some more tweaking but getting there

**Comment by GeorgeFive** [comment]
Sounds good!  Take your time, I don't have much time through the week to play with code, so I'm a bit out of commission until the weekend, haha.

**Comment by duck7000** [comment]
I've got it working, took me a while to figure it all out.

In principle i can add all methods (except the artist search) in advanced title class?
fetchData from title class can be included as well. (image urls would be also included in the cache)
both search functions to do text search (title and advanced) would not be included as this has little value and would/could clog up the amount of cache files.

You do realize that caching a lot of results would quickly fill up your disc space though

**Comment by GeorgeFive** [comment]
> You do realize that caching a lot of results would quickly fill up your disc space though

Are the cache files a lot larger here than on imdbphp?  I use caching over there with pruning, and right this second, I have 439 cached files, clocking in at 277kb.  I was figuring musicbrainz would be in the same general area?

**Comment by duck7000** [comment]
The size of the cache files is not that big, how many files is/might be a bigger issue as there are more methods involved.

For a single Artist there is release groups, releases and possibly fetchData to be cached so at least 3 files per artist.
Image urls would add to that, so total 4

So no it is not a big issue i guess but i would advise you to check those cache files after a while of using the classes to see how many there are and what size it total is.

**Comment by GeorgeFive** [comment]
I think in my use case, if we have a cacheExpire setting like in imdbphp, I would definitely be fine.  If not, I have my own cleanup function that cleans old sql cache files, auto-generated thumbnails, etc automatically and I could just toss this folder into the queue.

I would say fetchReleaseGroups and releaseGroupReleases for sure, those are the most important, I think.  fetchData is a maybe.  I wouldn't complain if it was there, but I don't think I NEED it.

**Comment by duck7000** [comment]
cache expire setting is in config so that is not a problem

I will add those 2 methods, fetchData is indeed a maybe. I expect that the data from fetchData not often is reused so for now i will leave it out.
If it turns out it is still handy/needed i can add it later

**Comment by duck7000** [comment]
Caching is now here in my test environment working on those 2 methods.

I will upload it when i have the time

**Comment by GeorgeFive** [comment]
Sounds good!

**Comment by duck7000** [comment]
I just uploaded, latest git version.

Check it out!

**Comment by GeorgeFive** [comment]
hmmm... I'm actually not getting anything cached?  I changed the config values, made the folder (and writable), uploaded all new files... and nothing?

**Comment by duck7000** [comment]
Did you enable both cache parts in config, cacheUse and cacheStore?

it is working here with the latest uploaded files

**Comment by GeorgeFive** [comment]
Yep and yep.... cacheUseZip is also true, cacheConvertZip is false... same settings I use for imdb.

I use tmp/imdbphp and tmp/musicbrainz... both set to 0755 (also tried 0777 just to test).... imdb works, MB doesn't.

**Comment by duck7000** [comment]
Is that directory writable by web server user?

I use here a directory inside musicBrainz (outside src folder) and my path in config is ./cache/

**Comment by GeorgeFive** [comment]
Yep... user permissions are ok (same as imdb), and file permissions are as well.

[root@host ~]#  cd /home/mvmmdi/public_html/tmp/
[root@host tmp]# ll
total 24420
drwxr-xr-x 2 mvmmdi mvmmdi  1654784 Jun 29 14:23 imdbphp
drwxr-xr-x 2 mvmmdi mvmmdi     4096 Jun 29 15:50 musicbrainz

I also tried changing the musicbrainz folder to 0777 (full write), and that didn't work either.  The functions are working properly and getting data, but there's just no cache.

**Comment by GeorgeFive** [comment]
Did you upload the newest files?  I see nothing in, for example, TitleSearchAdvanced.php related to caching.

**Comment by duck7000** [comment]
cache functions are in API.php not in TitleSearchAdvanced

**Comment by GeorgeFive** [comment]
I'm really not sure what's going on... I just redownloaded the files again just to be sure, double-checked config (all good, tried changing a few values), folder is writable and fine.

I just went through a full run of functions....

searchArtist
fetchReleaseGroups
releaseGroupReleases
fetchData

And nothing is cached...?  I know not everything is cached, but I get nothing.

**Comment by GeorgeFive** [comment]
Ok, now I really don't know what's going on... caching is now working.  I found this out while testing something and wondering why it wasn't updating when I was changing parameters.  In fact, the only thing I changed was my own framework, which should have had no effect....???? I have no idea.

Anyway.  Can you put type into the cache parameters for doReleaseGroupSearch?  As is, it will cache the results regardless of type selected.  So, if I do....

$music->fetchReleaseGroups($artist, "discography")

...that will get the proper results and cache them.  Cool!  But if I then do...

$music->fetchReleaseGroups($artist, "all");

,,,we will get the cached results for "discography".

**Comment by duck7000** [comment]
Mm good point about type, never thought of that..

I'll look in to that

**Comment by duck7000** [comment]
@GeorgeFive 
This is fixed in latest git, check it out if you have the time.

We are getting there to make everything work like you want hah

**Comment by GeorgeFive** [comment]
Looks good!  And yeah, this is going to be an adventure, haha.

**Comment by GeorgeFive** [comment]
Yep, all good! I don't really think we need fetchdata cached. I mean, I wouldn't complain if you or someone else wanted it, but personally, I don't really need it. 

Thanks!

**Comment by duck7000** [comment]
As a final comment, you had issues with caching but i hope you realize that caching is default disabled in config?
So with a new version caching is off, you have to set that to enable every time, same behavior as imdbGraphQLPHP

**Comment by GeorgeFive** [comment]
Yep, I'm not sure what happened there. I never overwrite my config file, I just check to see if there's any changes.

**Comment by duck7000** [comment]
I'll see if i can make that happen.

I don't have much time though, there is a fatal medical issue in the family

**Comment by GeorgeFive** [comment]
I'm sorry to hear that!  Take your time, real world stuff always takes priority over this stuff.

**Comment by duck7000** [comment]
Thanks, real life stuff happens i'm afraid

**Comment by duck7000** [comment]
I am thinking about this, i can make this happen of course but how about the image urls?
Those won't be cached as they come from a separate method, i don't know if this is a problem but it will affect speed

**Comment by GeorgeFive** [comment]
That shouldn't be an issue.  I mean, the more that is cached, the better, but if certain things can't be handled, that's totally understandable.

**Comment by duck7000** [comment]
@GeorgeFive 
I uploaded changes to fetchData()
Caching is now possible for fetchData() including the cover urls from release and release group

It is a little bit hacky in the cache function but it works

check it out and let me know how it works

**Comment by GeorgeFive** [comment]
Looks good!  I noticed there's no caching on the new v/a releases function, want to put it over there when you get the time?  No rush!

**Comment by duck7000** [comment]
yes there is no caching on VA and artist bio, it is too complicated to make that work. The output of all those different methods is a problem with my cache function

I made a kind of system to make everything work, but as there are more methods added my system does not work anymore so i have to adjust it to make it happen. I did all adjustments to make fetchData be able to use cache

**Comment by GeorgeFive** [comment]
Ok, if it's too complicated, it's not a huge issue.  I'm just trying to reduce calls as much as possible, especially on pages like this where I'll probably be reloading numerous times (especially during testing and dev on my side).

**Comment by duck7000** [comment]
I'll try, it might be possible but no guarantees hah

**Comment by duck7000** [comment]
Well after looking in to this it wasn't that hard to get it working after all.

So this is added in latest commit.

**Comment by GeorgeFive** [comment]
I do believe it is!  I can't think of anywhere else off the top of my head...

**Comment by duck7000** [comment]
Nice, thanks for testing!

**Comment by GeorgeFive** [comment]
Just found an issue with this... if an album has no coverart, the function will crash.

album id - 6d15afa8-ee09-4468-b5cf-dd92d528fb5f

[25-Jul-2024 11:33:48 EST] PHP Fatal error:  Uncaught Exception: Failed to retrieve query in classes/MusicBrainzPHP/src/Music/API.php:249
Stack trace:
#0 classes/MusicBrainzPHP/src/Music/API.php(294): Music\Api->execRequest('https://coverar...')
#1 classes/MusicBrainzPHP/src/Music/API.php(227): Music\Api->checkCache('4cbf403e-4e3d-3...', 'https://coverar...', 'title', '_rgidCover')
#2 classes/MusicBrainzPHP/src/Music/Title.php(452): Music\Api->doCoverArtLookupRelGroup('4cbf403e-4e3d-3...')
#3 classes/MusicBrainzPHP/src/Music/Title.php(393): Music\Title->fetchCoverArt(true)
#4 admin/get_musicbrainz_info.php(386): Music\Title->fetchData()
#5 admin/get_musicbrainz_info.php(60): getAlbumInfo('6d15afa8-ee09-4...')
#6 admin/get_musicbrainz_info.php(15): main('6d15afa8-ee09-4...', 'album')
#7 {main}

**Comment by duck7000** [comment]
Huh this can't be with fetchArtistBio() there is no coverart in there..

**Comment by GeorgeFive** [comment]
Nah, it's a general cache issue.  Github decided to convert my pound sign / numbers in the error log to references to other issues.

**Comment by duck7000** [comment]
so it is no issue with this library or method?

**Comment by GeorgeFive** [comment]
This is the caching thread?  I'm confused, hah. This has started popping up since caching was added to coverart, I just noticed it earlier.

**Comment by duck7000** [comment]
the coverart is fixed in latest commit, i did have a fix for this but forget to implant it back in the cache method

**Comment by GeorgeFive** [comment]
Looking good, thanks!
