### ISSUE TITLE
Releasegroup artwork

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#6]
When grabbing the artwork for an album, should we also grab the releasegroup artwork?

Example - no artwork - https://musicbrainz.org/release/f7c680af-5b09-3fea-be84-5e00a7da56a0
Example - bad image - https://musicbrainz.org/release/a5985d9e-d38f-4625-9639-d6790d98a0d4

But the releasegroup that these albums belong to has perfectly fine artwork - https://musicbrainz.org/release-group/d3bc1a64-7561-3787-b680-0003aa50f8f1

The url is pretty simple - https://coverartarchive.org/release-group/(releasegroup id)/front, ie https://coverartarchive.org/release-group/d3bc1a64-7561-3787-b680-0003aa50f8f1/front

If you think it's useful, you could throw that in as an option?  If not, I can just handle it manually in my own code.

**Comment by duck7000** [comment]
This is something weird, in the documentation they mention that the images from release groups actually comes from the releases inside that group but your example shows that isn't the case?

Your last url (stripped of /front) gives all images inside that group but only front images are supported nothing else

maybe i can make a method to get release group image urls just as i use the method for the release images
I'll think about it.

**Comment by GeorgeFive** [comment]
I'm actually not sure how they handle this.  I know that there's 51 versions of Back In Black, and I've clicked a handful of them... some of them have good quality artwork, some have bad quality (flashes, crooked, CD case included, etc), and some simply have no artwork.

The problem I'm facing in my framework, is if I want to use the "best" version of the album in that releasegroup, I have to hope that that version of the album also has good artwork.  In this instance, if I pick the original US or UK vinyl release of the album, I'll get no artwork.  If I pick the original AUS vinyl version, I do get artwork, but a later release date and the Australian label instead of the much more common label (Atlantic).

**Comment by duck7000** [comment]
I understand the problem but there isn't a simple solution to that.
You, as human, would have to check if the image is acceptable or not.

The only option i see is to get an array of all image urls inside a releasegroup (from the titles inside that group, not the group itself). You can use the array to show all those images and pick one you want?
I'm not sure this could work though and it will complicate stuff

I have the same problem with discogs in my cd database program, if a release does not have a acceptable image i have to choose another release that does.

This needs way more thinking through i guess

**Comment by GeorgeFive** [comment]
> The only option i see is to get an array of all image urls inside a releasegroup

If that is possible, that will probably be the easiest way to do it.  I do plan on checking manually, so that's not an issue.  If it's not an option, I think the releasegroup album art would probably suffice, it's usually the best version.

**Comment by duck7000** [comment]
i'm going to try

**Comment by duck7000** [comment]
@GeorgeFive 
I thought about this for a while and getting all image urls from all releases inside a release group might be a bridge too far.

So i'm going to work on something that will get the release group images.
This would/will be a separate method i guess?
Or does it have to be included in fetchData()?

**Comment by GeorgeFive** [comment]
I think including this in fetchData would be simpler, but if it's another method, I don't think I would complain too much.  Whichever is easier on your end!

**Comment by GeorgeFive** [comment]
Awesome! I will check it out when I get home from work tonight.

**Comment by GeorgeFive** [comment]
All seemed to work pretty well, didn't spot any issues!

**Comment by duck7000** [comment]
Nice, thanks for testing.

There still might be a issue, if there are no cover images in the release group a exception is thrown and the script will break.
I try to fix that but it is difficult as it is all connected to each other

**Comment by GeorgeFive** [comment]
I hadn't come across that, to be honest... but now I do see it.

**Comment by duck7000** [comment]
do you mean you have a example?
Or you spotted the potential problem in api.php?

**Comment by GeorgeFive** [comment]
Yep... album id
e5e2a715-01c6-4f4b-9523-1e9d2fda7111

**Comment by duck7000** [comment]
I fixed this in latest commit
