### ISSUE TITLE
Secondary types

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/MusicBrainzPHP#8]
Hey, hopefully an easy request... can we get secondary album types in title.php?  The exact same thing that we have in titlesearchadvanced.

**Comment by duck7000** [comment]
Sure we can, i'll try to fix that

**Comment by duck7000** [comment]
Do you have a example release id that has a secondary type listed?

It might be that for a single release there is only one type? (the primary type)

**Comment by duck7000** [comment]
I just uploaded changes for secondary types

This is release group secondary types as there are secondary types for the release itself

**Comment by GeorgeFive** [comment]
Awesome, will check it out after work!

**Comment by GeorgeFive** [comment]
Perfect!

**Comment by duck7000** [comment]
Thanks!
